### PR TITLE
Fix permission error in system module discovery

### PR DESCRIPTION
**Pull request by Paul1365972**
Stops crashing when system path contains a directory which we don't have permission to read

### CODE REVIEW

**Comment by ErikBjare** [comment]
Oh, nice. Just one comment :)

**Comment by Paul1365972** [comment]
It was on my windows system after an docker desktop update added the path variable "C:/ProgramData/Docker/bin-ver" (or something close to that not sure as I am on mobile right now)

**Comment by ErikBjare** [comment]
I forgot about this and committed this yesterday: https://github.com/ActivityWatch/aw-qt/commit/0286a4852be19ef0a0196cf17f15adc618cfd64d

Is this PR still needed?

**Comment by Paul1365972** [comment]
No, thanks for fixing it!

**Pull request closed without merging**
